library(ggplot2)
library(ggthemes)

data <- read.csv("/home/jmerelo/Documentos/COVID.HMhospitales/01.csv",sep=";")
data$SEXO.SEX <- as.factor(data$SEXO.SEX)
data$MOTIVO_ALTA.DESTINY_DISCHARGE_ING <- as.factor(data$MOTIVO_ALTA.DESTINY_DISCHARGE_ING)
data$ingreso <- as.Date(data$F_INGRESO.ADMISSION_D_ING.INPAT,format="%d/%m/%Y")
data$salida <- as.Date(data$F_ALTA.DISCHARGE_DATE_ING, format="%d/%m/%Y")
data$duracion <- as.numeric( data$salida - data$ingreso )
ggplot(data, aes(x=MOTIVO_ALTA.DESTINY_DISCHARGE_ING,y=duracion,color=MOTIVO_ALTA.DESTINY_DISCHARGE_ING))+geom_tufteboxplot()
